/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package calculator;

import java.awt.Color;
import static java.awt.event.KeyEvent.*;
import java.math.BigDecimal;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import sun.org.mozilla.javascript.internal.ScriptRuntime;

/**
 *
 * @author lib
 */
public class standard_cal extends javax.swing.JFrame {

    /**
     * Creates new form standard_cal
     */
    String result, op1, op2, operator;
    int result_setter;
    int count = 0;

    public standard_cal() {
        initComponents();
        this.setLocation(400, 150);
        operand_bar.setEnabled(false);
        operand_bar.setHorizontalAlignment(JTextField.RIGHT);
        stand_input.setHorizontalAlignment(JTextField.RIGHT);
        operand_bar.setText("");
        stand_input.setText("");
        operator = "";
        set_color_focus_button();
        stand_input.setFocusable(true);
        stand_input.requestFocusInWindow();
        setBounds(400,150, 340, 330);
        result=String.valueOf(0);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        plus1 = new javax.swing.JButton();
        multi1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        nine = new javax.swing.JButton();
        precent = new javax.swing.JButton();
        six = new javax.swing.JButton();
        decimal = new javax.swing.JButton();
        five = new javax.swing.JButton();
        minus = new javax.swing.JButton();
        four = new javax.swing.JButton();
        plus = new javax.swing.JButton();
        three = new javax.swing.JButton();
        stand_del = new javax.swing.JButton();
        two = new javax.swing.JButton();
        one = new javax.swing.JButton();
        reset = new javax.swing.JButton();
        zero = new javax.swing.JButton();
        bt_equal = new javax.swing.JButton();
        seven = new javax.swing.JButton();
        eight = new javax.swing.JButton();
        dzero = new javax.swing.JButton();
        sqrt = new javax.swing.JButton();
        division = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        one_byx = new javax.swing.JButton();
        plus_minus = new javax.swing.JButton();
        operand_bar = new javax.swing.JLabel();
        stand_input = new javax.swing.JLabel();
        multi = new javax.swing.JButton();
        menu_bar = new javax.swing.JMenuBar();
        view_menu = new javax.swing.JMenu();
        view_standard = new javax.swing.JMenuItem();
        view_sciencetific = new javax.swing.JMenuItem();
        view_programmer = new javax.swing.JMenuItem();
        close = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        edit_copy = new javax.swing.JMenuItem();
        edit_paste = new javax.swing.JMenuItem();
        help_menu = new javax.swing.JMenu();
        help_show = new javax.swing.JMenuItem();
        update = new javax.swing.JMenuItem();

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("        Standrad");

        plus1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        plus1.setText("+");
        plus1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                plus1ActionPerformed(evt);
            }
        });

        multi1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        multi1.setText("*");
        multi1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                multi1ActionPerformed(evt);
            }
        });

        jLabel4.setText("jLabel4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Standard");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                formFocusGained(evt);
            }
        });
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });
        getContentPane().setLayout(null);

        nine.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        nine.setText("9");
        nine.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nineMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                nineMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                nineMouseExited(evt);
            }
        });
        nine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nineActionPerformed(evt);
            }
        });
        nine.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                nineKeyTyped(evt);
            }
        });
        getContentPane().add(nine);
        nine.setBounds(20, 100, 47, 40);

        precent.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        precent.setText("%");
        precent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                precentActionPerformed(evt);
            }
        });
        getContentPane().add(precent);
        precent.setBounds(170, 180, 45, 40);

        six.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        six.setText("6");
        six.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                sixMouseEntered(evt);
            }
        });
        six.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sixActionPerformed(evt);
            }
        });
        getContentPane().add(six);
        six.setBounds(20, 140, 47, 40);

        decimal.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        decimal.setText(".");
        decimal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                decimalActionPerformed(evt);
            }
        });
        getContentPane().add(decimal);
        decimal.setBounds(120, 220, 49, 35);

        five.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        five.setText("5");
        five.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fiveActionPerformed(evt);
            }
        });
        getContentPane().add(five);
        five.setBounds(70, 140, 47, 40);

        minus.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        minus.setText("-");
        minus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                minusActionPerformed(evt);
            }
        });
        getContentPane().add(minus);
        minus.setBounds(220, 180, 50, 40);

        four.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        four.setText("4");
        four.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fourActionPerformed(evt);
            }
        });
        getContentPane().add(four);
        four.setBounds(120, 140, 49, 40);

        plus.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        plus.setText("+");
        plus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                plusActionPerformed(evt);
            }
        });
        getContentPane().add(plus);
        plus.setBounds(220, 220, 100, 36);

        three.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        three.setText("3");
        three.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                threeMouseEntered(evt);
            }
        });
        three.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                threeActionPerformed(evt);
            }
        });
        getContentPane().add(three);
        three.setBounds(20, 180, 47, 40);

        stand_del.setText("←");
        stand_del.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                stand_delMouseEntered(evt);
            }
        });
        stand_del.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stand_delActionPerformed(evt);
            }
        });
        getContentPane().add(stand_del);
        stand_del.setBounds(220, 100, 50, 40);

        two.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        two.setText("2");
        two.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                twoActionPerformed(evt);
            }
        });
        getContentPane().add(two);
        two.setBounds(70, 180, 47, 40);

        one.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        one.setText("1");
        one.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oneActionPerformed(evt);
            }
        });
        getContentPane().add(one);
        one.setBounds(120, 180, 49, 40);

        reset.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        reset.setText("c");
        reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetActionPerformed(evt);
            }
        });
        getContentPane().add(reset);
        reset.setBounds(271, 100, 50, 40);

        zero.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        zero.setText("0");
        zero.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                zeroMouseEntered(evt);
            }
        });
        zero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zeroActionPerformed(evt);
            }
        });
        getContentPane().add(zero);
        zero.setBounds(20, 220, 47, 36);

        bt_equal.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        bt_equal.setText("=");
        bt_equal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_equalActionPerformed(evt);
            }
        });
        getContentPane().add(bt_equal);
        bt_equal.setBounds(170, 220, 45, 36);

        seven.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        seven.setText("7");
        seven.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sevenActionPerformed(evt);
            }
        });
        getContentPane().add(seven);
        seven.setBounds(120, 100, 49, 40);

        eight.setFont(eight.getFont().deriveFont(eight.getFont().getStyle() | java.awt.Font.BOLD));
        eight.setText("8");
        eight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eightActionPerformed(evt);
            }
        });
        getContentPane().add(eight);
        eight.setBounds(70, 100, 47, 40);

        dzero.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        dzero.setText("00");
        dzero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dzeroActionPerformed(evt);
            }
        });
        getContentPane().add(dzero);
        dzero.setBounds(70, 220, 47, 35);

        sqrt.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        sqrt.setText("√");
        sqrt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sqrtActionPerformed(evt);
            }
        });
        getContentPane().add(sqrt);
        sqrt.setBounds(270, 140, 50, 40);

        division.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        division.setText("/");
        division.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                divisionActionPerformed(evt);
            }
        });
        getContentPane().add(division);
        division.setBounds(220, 140, 50, 40);

        jLabel2.setText("© pankaj&company                        All Rights Reserved");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 260, 290, 24);

        one_byx.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        one_byx.setText("1/x");
        one_byx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                one_byxActionPerformed(evt);
            }
        });
        getContentPane().add(one_byx);
        one_byx.setBounds(170, 100, 47, 40);

        plus_minus.setText("± ");
        plus_minus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                plus_minusMouseEntered(evt);
            }
        });
        plus_minus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                plus_minusActionPerformed(evt);
            }
        });
        getContentPane().add(plus_minus);
        plus_minus.setBounds(170, 140, 45, 40);

        operand_bar.setBackground(new java.awt.Color(255, 255, 51));
        operand_bar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        operand_bar.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        operand_bar.setOpaque(true);
        getContentPane().add(operand_bar);
        operand_bar.setBounds(20, 20, 300, 40);

        stand_input.setBackground(new java.awt.Color(255, 255, 255));
        stand_input.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        stand_input.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        stand_input.setOpaque(true);
        stand_input.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                stand_inputKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                stand_inputKeyTyped(evt);
            }
        });
        getContentPane().add(stand_input);
        stand_input.setBounds(20, 50, 300, 50);

        multi.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        multi.setText("*");
        multi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                multiActionPerformed(evt);
            }
        });
        getContentPane().add(multi);
        multi.setBounds(270, 180, 50, 40);

        view_menu.setText("View");
        view_menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                view_menuActionPerformed(evt);
            }
        });

        view_standard.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_1, java.awt.event.InputEvent.ALT_MASK));
        view_standard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/calculator/standard.png"))); // NOI18N
        view_standard.setText("Standard");
        view_standard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                view_standardActionPerformed(evt);
            }
        });
        view_standard.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                view_standardFocusGained(evt);
            }
        });
        view_menu.add(view_standard);

        view_sciencetific.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_2, java.awt.event.InputEvent.ALT_MASK));
        view_sciencetific.setIcon(new javax.swing.ImageIcon(getClass().getResource("/calculator/scientific.png"))); // NOI18N
        view_sciencetific.setText("Sciencetific");
        view_sciencetific.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                view_sciencetificActionPerformed(evt);
            }
        });
        view_menu.add(view_sciencetific);

        view_programmer.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_3, java.awt.event.InputEvent.ALT_MASK));
        view_programmer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/calculator/programmer.png"))); // NOI18N
        view_programmer.setText("Programmer");
        view_programmer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                view_programmerActionPerformed(evt);
            }
        });
        view_menu.add(view_programmer);

        close.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_MASK));
        close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/calculator/close.png"))); // NOI18N
        close.setText("Close");
        close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeActionPerformed(evt);
            }
        });
        view_menu.add(close);

        menu_bar.add(view_menu);

        jMenu2.setText("Edit");

        edit_copy.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
        edit_copy.setIcon(new javax.swing.ImageIcon(getClass().getResource("/calculator/edit_copy.png"))); // NOI18N
        edit_copy.setText("Copy");
        jMenu2.add(edit_copy);

        edit_paste.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.CTRL_MASK));
        edit_paste.setIcon(new javax.swing.ImageIcon(getClass().getResource("/calculator/edit_paste.png"))); // NOI18N
        edit_paste.setText("Paste");
        jMenu2.add(edit_paste);

        menu_bar.add(jMenu2);

        help_menu.setText("Help");

        help_show.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, 0));
        help_show.setIcon(new javax.swing.ImageIcon(getClass().getResource("/calculator/help.png"))); // NOI18N
        help_show.setText("View Help");
        help_show.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                help_showActionPerformed(evt);
            }
        });
        help_menu.add(help_show);

        update.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, java.awt.event.InputEvent.ALT_MASK));
        update.setIcon(new javax.swing.ImageIcon(getClass().getResource("/calculator/system_update.png"))); // NOI18N
        update.setText("Check for update");
        help_menu.add(update);

        menu_bar.add(help_menu);

        setJMenuBar(menu_bar);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nineActionPerformed
        // TODO add your handling code here:
        if (check_for_retype() == 1) {
            stand_input.setText("");
            result_setter = 1;
        }
        stand_input.setText(stand_input.getText() + "9");
    }//GEN-LAST:event_nineActionPerformed

    private void precentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_precentActionPerformed
        // TODO add your handling code here:
    if(operand_bar.getText().endsWith(")"))
    {
        operand_bar.setText(operand_bar.getText()+"%");
    }
    else
    {
        if (operator.equals("=") && count != 0) {
            operand_bar.setText("");
            result = stand_input.getText();
            operand_bar.setText(result);
            count = 0;
        } else {
            if (count++ == 0) {
                result = op1 = stand_input.getText();
                operator = "%";
                // cal(op1,operator);
                operand_bar.setText(operand_bar.getText() + op1 + "%");
                
            } else {
                op2 = stand_input.getText();
                cal(op2, operator);
                operator = "%";
                operand_bar.setText(operand_bar.getText() + op2 + "%");
                stand_input.setText(result);
            }
        }
      }
    }//GEN-LAST:event_precentActionPerformed

    private void sixActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sixActionPerformed
        // TODO add your handling code here:
        if (check_for_retype() == 1) {
            stand_input.setText("");
            result_setter = 1;
        }
        stand_input.setText(stand_input.getText() + "6");
    }//GEN-LAST:event_sixActionPerformed

    private void fiveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fiveActionPerformed
        // TODO add your handling code here:
        if (check_for_retype() == 1) {
            stand_input.setText("");
            result_setter = 1;
        }
        stand_input.setText(stand_input.getText() + "5");
    }//GEN-LAST:event_fiveActionPerformed

    private void minusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minusActionPerformed
        // TODO add your handling code here:
    if(operand_bar.getText().endsWith(")"))
    {
        operand_bar.setText(operand_bar.getText()+"-");
    }
    else
    {
        if (operator.equals("=") && count != 0) {
            operand_bar.setText("");
            result = stand_input.getText();
            stand_input.setText("");
            operand_bar.setText(result);
            count = 0;
        } else {
            if (count++ == 0) {
                result = op1 = stand_input.getText();
                operator = "-";
                //cal(op1,operator);
                operand_bar.setText(operand_bar.getText() + op1 + "-");
            } else {
                op2 = stand_input.getText();
                cal(op2, operator);
                operator = "-";
                operand_bar.setText(operand_bar.getText() + op2 + "-");
                stand_input.setText(result);
            }
        }
      }
    }//GEN-LAST:event_minusActionPerformed

    private void fourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fourActionPerformed
        // TODO add your handling code here:
        if (check_for_retype() == 1) {
            stand_input.setText("");
            result_setter = 1;
        }
        stand_input.setText(stand_input.getText() + "4");
    }//GEN-LAST:event_fourActionPerformed

    private void plusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_plusActionPerformed
        // TODO add your handling code here:
    if(operand_bar.getText().endsWith(")"))
    {
        operand_bar.setText(operand_bar.getText()+"+");
    }
    else
    {
        if (operator.equals("=") && count != 0) {
            operand_bar.setText("");
            result = stand_input.getText();
            // stand_input.setText("");
            operator = "+";
            operand_bar.setText(result + operator);
            count = 0;
        } else {
            if (count++ == 0) {
                result = op1 = stand_input.getText();
                operator = "+";
                //cal(op1,operator);
                operand_bar.setText(operand_bar.getText() + op1 + "+");
            } else {
                op2 = stand_input.getText();
                cal(op2, operator);
                operator = "+";
                operand_bar.setText(operand_bar.getText() + op2 + "+");
                stand_input.setText(result);
            }
        }
     }
    }//GEN-LAST:event_plusActionPerformed

    private void threeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_threeActionPerformed
        // TODO add your handling code here:
        if (check_for_retype() == 1) {
            stand_input.setText("");
            result_setter = 1;
        }
        stand_input.setText(stand_input.getText() + "3");
    }//GEN-LAST:event_threeActionPerformed

    private void twoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_twoActionPerformed
        // TODO add your handling code here:
        if (check_for_retype() == 1) {
            stand_input.setText("");
            result_setter = 1;
        }
        stand_input.setText(stand_input.getText() + "2");
    }//GEN-LAST:event_twoActionPerformed

    private void oneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oneActionPerformed
        // TODO add your handling code here:
        if (check_for_retype() == 1) {
            stand_input.setText("");
            result_setter = 1;
        }
        stand_input.setText(stand_input.getText() + "1");
    }//GEN-LAST:event_oneActionPerformed

    private void resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetActionPerformed
        // TODO add your handling code here:
        stand_input.setText("");
        operand_bar.setText("");
        count = 0;
        result = String.valueOf(0);
    }//GEN-LAST:event_resetActionPerformed

    private void zeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zeroActionPerformed
        // TODO add your handling code here:
        if (check_for_retype() == 1) {
            stand_input.setText("");
            result_setter = 1;
        }
        stand_input.setText(stand_input.getText() + "0");
        
    }//GEN-LAST:event_zeroActionPerformed

    private void bt_equalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_equalActionPerformed
        // TODO add your handling code here:
        op2 = stand_input.getText();
        if (!op2.equals("")) {
            cal(op2, operator);
            operand_bar.setText(operand_bar.getText() + op2);
            stand_input.setText("");
            stand_input.setText(result);
            operator = "=";
            //count=0;
        } else {
            JOptionPane.showMessageDialog(null, " illegal Expression ", "Error!!", 1);
        }
    }//GEN-LAST:event_bt_equalActionPerformed

    private void sevenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sevenActionPerformed
        // TODO add your handling code here:
        if (check_for_retype() == 1) {
            stand_input.setText("");
            result_setter = 1;
        }
        stand_input.setText(stand_input.getText() + "7");
    }//GEN-LAST:event_sevenActionPerformed

    private void eightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eightActionPerformed
        // TODO add your handling code here:
        if (check_for_retype() == 1) {
            stand_input.setText("");
            result_setter = 1;
        }
        stand_input.setText(stand_input.getText() + "8");
    }//GEN-LAST:event_eightActionPerformed

    private void dzeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dzeroActionPerformed
        // TODO add your handling code here:
        if (check_for_retype() == 1) {
            stand_input.setText("");
            result_setter = 1;
        }
        stand_input.setText(stand_input.getText() + "00");
    }//GEN-LAST:event_dzeroActionPerformed

    private void sqrtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sqrtActionPerformed
        String temp_for_tego;
        if(stand_input.getText().equals(""))
            {
               operand_bar.setText(operand_bar.getText()+"sqrt("+"0"+")"); 
               temp_for_tego=String.valueOf(Math.sqrt(0));
            }
            else
            {
            operand_bar.setText(operand_bar.getText()+"sqrt("+stand_input.getText()+")");
            temp_for_tego=String.valueOf((Math.sqrt((Double.valueOf(stand_input.getText())))));
            }
            cal(temp_for_tego, operator);
            stand_input.setText(result);
    }//GEN-LAST:event_sqrtActionPerformed

    private void divisionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_divisionActionPerformed
        // TODO add your handling code here:
    if(operand_bar.getText().endsWith(")"))
    {
        operand_bar.setText(operand_bar.getText()+"/");
    }
    else
    {
        if (operator.equals("=") && count != 0) {
            operand_bar.setText("");
            result = stand_input.getText();
            stand_input.setText("");
            operand_bar.setText(result);
            count = 0;
        } else {
            if (count++ == 0) {
                result = op1 = stand_input.getText();
                operator = "/";
                // cal(op1,operator);
                operand_bar.setText(operand_bar.getText() + op1 + "/");
            } else {
                op2 = stand_input.getText();
                cal(op2, operator);
                operator = "/";
                operand_bar.setText(operand_bar.getText() + op2 + "/");
                stand_input.setText(result);
            }
        }
      }
    }//GEN-LAST:event_divisionActionPerformed

    private void view_standardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_view_standardActionPerformed
        // TODO add your handling code here:
        standard_cal st = new standard_cal();
        st.setVisible(true);
        dispose();
    }//GEN-LAST:event_view_standardActionPerformed

    private void view_standardFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_view_standardFocusGained
        // TODO add your handling code here:

    }//GEN-LAST:event_view_standardFocusGained

    private void view_sciencetificActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_view_sciencetificActionPerformed
        // TODO add your handling code here:
        scientific_cal sc = new scientific_cal();        
        sc.setVisible(true);
        dispose();
    }//GEN-LAST:event_view_sciencetificActionPerformed

    private void view_programmerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_view_programmerActionPerformed
        // TODO add your handling code here:
        programmer_cal pr = new programmer_cal();
        pr.setVisible(true);
        dispose();        
    }//GEN-LAST:event_view_programmerActionPerformed

    private void closeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_closeActionPerformed

    private void view_menuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_view_menuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_view_menuActionPerformed

    private void help_showActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_help_showActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_help_showActionPerformed

    private void decimalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_decimalActionPerformed
        // TODO add your handling code here:
        if (check_for_retype() == 1) {
            stand_input.setText("");
            result_setter = 1;
        }
        stand_input.setText(stand_input.getText() + ".");
    }//GEN-LAST:event_decimalActionPerformed

    private void stand_delActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stand_delActionPerformed
        // TODO add your handling code here:
        int len = stand_input.getText().length();
        if (len != 0) {
            String input = stand_input.getText();
            stand_input.setText(input.substring(0, len - 1));
        }
    }//GEN-LAST:event_stand_delActionPerformed

    private void stand_delMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_stand_delMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_stand_delMouseEntered

    private void formFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_formFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_formFocusGained

    private void one_byxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_one_byxActionPerformed
        // TODO add your handling code here:
        stand_input.setText(String.valueOf(1 / Float.valueOf(stand_input.getText())));
    }//GEN-LAST:event_one_byxActionPerformed

    private void plus_minusMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_plus_minusMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_plus_minusMouseEntered

    private void plus_minusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_plus_minusActionPerformed
        // TODO add your handling code here:
        stand_input.setText(String.valueOf(Float.valueOf(stand_input.getText()) * (-1)));
    }//GEN-LAST:event_plus_minusActionPerformed

    private void multi1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_multi1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_multi1ActionPerformed

    private void plus1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_plus1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_plus1ActionPerformed

    private void nineMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nineMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_nineMouseEntered

    private void nineMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nineMouseExited
        // TODO add your handling code here:
        //  nine.setBackground(Color.);
    }//GEN-LAST:event_nineMouseExited

    private void nineMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nineMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_nineMouseClicked

    private void sixMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sixMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_sixMouseEntered

    private void threeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_threeMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_threeMouseEntered

    private void zeroMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_zeroMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_zeroMouseEntered

    private void stand_inputKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_stand_inputKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_stand_inputKeyTyped

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_formKeyPressed

    private void stand_inputKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_stand_inputKeyPressed
        // TODO add your handling code here:
        keyboard(evt.getKeyCode());
    }//GEN-LAST:event_stand_inputKeyPressed

    private void nineKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nineKeyTyped
        // TODO add your handling code here:
        
    }//GEN-LAST:event_nineKeyTyped

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        stand_input.requestFocus();
    }//GEN-LAST:event_formWindowOpened

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        stand_input.requestFocus();
    }//GEN-LAST:event_formWindowActivated

    private void multiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_multiActionPerformed
        // TODO add your handling code here:
    if(operand_bar.getText().endsWith(")"))
    {
        operand_bar.setText(operand_bar.getText()+"*");
    }
    else
    {
        if (operator.equals("=") && count != 0) {
            operand_bar.setText("");
            result = stand_input.getText();
            // stand_input.setText("");
            operator = "*";
            operand_bar.setText(result + operator);
            count = 0;
        } else {
            if (count++ == 0) {
                result = op1 = stand_input.getText();
                operator = "*";
                //cal(op1,operator);
                operand_bar.setText(operand_bar.getText() + op1 + "*");
            } else {
                op2 = stand_input.getText();
                cal(op2, operator);
                operator = "*";
                operand_bar.setText(operand_bar.getText() + op2 + "*");
                stand_input.setText(result);
            }
        }
      }
    }//GEN-LAST:event_multiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(standard_cal.class.getName()).log(java.util.logging.Level.SEVERE, "", ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(standard_cal.class.getName()).log(java.util.logging.Level.SEVERE, "", ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(standard_cal.class.getName()).log(java.util.logging.Level.SEVERE, "", ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(standard_cal.class.getName()).log(java.util.logging.Level.SEVERE, "", ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new standard_cal().setVisible(true);
            }
        });
    }

    public void set_color_focus_button() {
        one.setBackground(Color.white);
        one.setFocusable(false);
        two.setBackground(Color.white);
        two.setFocusable(false);
        three.setBackground(Color.white);
        three.setFocusable(false);
        four.setBackground(Color.white);
        four.setFocusable(false);
        five.setBackground(Color.white);
        five.setFocusable(false);
        six.setBackground(Color.white);
        six.setFocusable(false);
        seven.setBackground(Color.white);
        seven.setFocusable(false);
        eight.setBackground(Color.white);
        eight.setFocusable(false);
        nine.setBackground(Color.white);
        nine.setFocusable(false);
        zero.setBackground(Color.white);
        zero.setFocusable(false);
        dzero.setBackground(Color.white);
        dzero.setFocusable(false);
        decimal.setBackground(Color.white);
        decimal.setFocusable(false);
        
        bt_equal.setBackground(Color.white);
        bt_equal.setFocusable(false);
        
        plus_minus.setBackground(Color.white);
        plus_minus.setFocusable(false);
        one_byx.setBackground(Color.white);
        one_byx.setFocusable(false);
        stand_del.setBackground(Color.white);
        stand_del.setFocusable(false);
        reset.setBackground(Color.white);
        reset.setFocusable(false);
        
        division.setBackground(Color.white);
        division.setFocusable(false);
        sqrt.setBackground(Color.white);
        sqrt.setFocusable(false);
        multi.setBackground(Color.white);
        multi.setFocusable(false);
        minus.setBackground(Color.white);
        minus.setFocusable(false);
        plus.setBackground(Color.white);
        plus.setFocusable(false);
        precent.setBackground(Color.white);
        precent.setFocusable(false);
        
    }

    public void cal(String second, String operator) {
        result_setter = 0;
        switch (operator) {
            case "+":
                result = String.valueOf(BigDecimal.valueOf(Double.valueOf(result) +Double.valueOf(second)));
                break;
            case "-":
                result = String.valueOf(BigDecimal.valueOf(Float.valueOf(result) - Float.valueOf(second)));
                break;
            case "*":
                result = String.valueOf(BigDecimal.valueOf(Float.valueOf(result) * Float.valueOf(second)));
                break;
            case "/":
                result = String.valueOf(BigDecimal.valueOf(Float.valueOf(result) / Float.valueOf(second)));
                break;
            case "%":
                result = String.valueOf(BigDecimal.valueOf(Float.valueOf(result) % Float.valueOf(second)));
                break;
            case "oneby":
                result = String.valueOf(BigDecimal.valueOf(1 / Float.valueOf(second)));
                break;
            default:
                result = second;
        }
    }

    public int check_for_retype() {
        int flag = 0;
        if (operand_bar.getText().endsWith("+") || operand_bar.getText().endsWith("-") || operand_bar.getText().endsWith("*") || operand_bar.getText().endsWith("/") || operand_bar.getText().endsWith("%")) {
            if (!result.equals("0") && result_setter == 0) {
                flag = 1;
            } else {
                flag = 0;
            }
        }
        return flag;
    }
    
    public void keyboard(int code)
    {
        switch (code)
        {
            case VK_0:
            case VK_NUMPAD0:
                if (check_for_retype() == 1) {
                    stand_input.setText("");
                    result_setter = 1;
                }
                stand_input.setText(stand_input.getText() + "0");
                break;
            case VK_1:
            case VK_NUMPAD1:
                if (check_for_retype() == 1) {
                    stand_input.setText("");
                    result_setter = 1;
                }
                stand_input.setText(stand_input.getText() + "1");
                break;
            case VK_2:
            case VK_NUMPAD2:
                if (check_for_retype() == 1) {
                    stand_input.setText("");
                    result_setter = 1;
                }
                stand_input.setText(stand_input.getText() + "2");
                break;
            case VK_3:
            case VK_NUMPAD3:
                if (check_for_retype() == 1) {
                    stand_input.setText("");
                    result_setter = 1;
                }
                stand_input.setText(stand_input.getText() + "3");
                break;
            case VK_4:
            case VK_NUMPAD4:
                if (check_for_retype() == 1) {
                    stand_input.setText("");
                    result_setter = 1;
                }
                stand_input.setText(stand_input.getText() + "4");
                break;
            case VK_5:
            case VK_NUMPAD5:
                if (check_for_retype() == 1) {
                    stand_input.setText("");
                    result_setter = 1;
                }
                stand_input.setText(stand_input.getText() + "5");
                break;
            case VK_6:
            case VK_NUMPAD6:
                if (check_for_retype() == 1) {
                    stand_input.setText("");
                    result_setter = 1;
                }
                stand_input.setText(stand_input.getText() + "6");
                break;
            case VK_7:
            case VK_NUMPAD7:
                if (check_for_retype() == 1) {
                    stand_input.setText("");
                    result_setter = 1;
                }
                stand_input.setText(stand_input.getText() + "7");
                break;
            case VK_8:
            case VK_NUMPAD8:
                if (check_for_retype() == 1) {
                    stand_input.setText("");
                    result_setter = 1;
                }
                stand_input.setText(stand_input.getText() + "8");
                break;
            case VK_9:
            case VK_NUMPAD9:
                if (check_for_retype() == 1) {
                    stand_input.setText("");
                    result_setter = 1;
                }
                stand_input.setText(stand_input.getText() + "9");
                break;
            case VK_BACK_SPACE:
                int len = stand_input.getText().length();
                if (len != 0) {
                    String input = stand_input.getText();
                    stand_input.setText(input.substring(0, len - 1));
                }
                break;
            case VK_PERIOD:
            case VK_DECIMAL:
                if (check_for_retype() == 1) {
                    stand_input.setText("");
                    result_setter = 1;
                }
                stand_input.setText(stand_input.getText() + ".");
                break;
            case VK_PLUS:
            case VK_ADD:
                if (operator.equals("=") && count != 0) {
                    operand_bar.setText("");
                    result = stand_input.getText();
                    operator = "+";
                    operand_bar.setText(result + operator);
                    count = 0;
                } else {
                    if (count++ == 0) {
                        result = op1 = stand_input.getText();
                        operator = "+";
                        operand_bar.setText(operand_bar.getText() + op1 + "+");
                    } else {
                        op2 = stand_input.getText();
                        cal(op2, operator);
                        operator = "+";
                        operand_bar.setText(operand_bar.getText() + op2 + "+");
                        stand_input.setText(result);
                        //System.out.println(D.valueOf(result));
                    }
                }
                break;
            case VK_MINUS:
            case VK_SUBTRACT:
                if (operator.equals("=") && count != 0) {
                    operand_bar.setText("");
                    result = stand_input.getText();
                    operator = "+";
                    operand_bar.setText(result + operator);
                    count = 0;
                } else {
                    if (count++ == 0) {
                        result = op1 = stand_input.getText();
                        operator = "-";
                        operand_bar.setText(operand_bar.getText() + op1 + "-");
                    } else {
                        op2 = stand_input.getText();
                        cal(op2, operator);
                        operator = "-";
                        operand_bar.setText(operand_bar.getText() + op2 + "-");
                        stand_input.setText(result);
                    }
                }
                break;
            case VK_MULTIPLY:
                if (operator.equals("=") && count != 0) {
                    operand_bar.setText("");
                    result = stand_input.getText();
                    operator = "*";
                    operand_bar.setText(result + operator);
                    count = 0;
                } else {
                    if (count++ == 0) {
                        result = op1 = stand_input.getText();
                        operator = "*";
                        operand_bar.setText(operand_bar.getText() + op1 + "*");
                    } else {
                        op2 = stand_input.getText();
                        cal(op2, operator);
                        operator = "*";
                        operand_bar.setText(operand_bar.getText() + op2 + "*");
                        stand_input.setText(result);
                    }
                }
                break;
            case VK_DIVIDE:
                if (operator.equals("=") && count != 0) {
                    operand_bar.setText("");
                    result = stand_input.getText();
                    operator = "/";
                    operand_bar.setText(result + operator);
                    count = 0;
                } else {
                    if (count++ == 0) {
                        result = op1 = stand_input.getText();
                        operator = "/";
                        operand_bar.setText(operand_bar.getText() + op1 + "/");
                    } else {
                        op2 = stand_input.getText();
                        cal(op2, operator);
                        operator = "/";
                        operand_bar.setText(operand_bar.getText() + op2 + "/");
                        stand_input.setText(result);
                    }
                }
                break;
            case VK_AMPERSAND:
                if (operator.equals("=") && count != 0) {
                    operand_bar.setText("");
                    result = stand_input.getText();
                    operator = "%";
                    operand_bar.setText(result + operator);
                    count = 0;
                } else {
                    if (count++ == 0) {
                        result = op1 = stand_input.getText();
                        operator = "%";
                        operand_bar.setText(operand_bar.getText() + op1 + "%");
                    } else {
                        op2 = stand_input.getText();
                        cal(op2, operator);
                        operator = "%";
                        operand_bar.setText(operand_bar.getText() + op2 + "%");
                        stand_input.setText(result);
                    }
                }
                break;
            case VK_ENTER:
                op2 = stand_input.getText();
                if (!op2.equals("")) {
                    cal(op2, operator);
                    operand_bar.setText(operand_bar.getText() + op2);
                    stand_input.setText("");
                    stand_input.setText(result);
                    operator = "=";
                } else {
                    JOptionPane.showMessageDialog(null, " illegal Expression ", "Error!!", 1);
                }
                break;
            case VK_SHIFT+VK_C:
                      stand_input.setText("");
                      operand_bar.setText("");
                      count = 0;
                       result = String.valueOf(0);
                break;
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_equal;
    private javax.swing.JMenuItem close;
    private javax.swing.JButton decimal;
    private javax.swing.JButton division;
    private javax.swing.JButton dzero;
    private javax.swing.JMenuItem edit_copy;
    private javax.swing.JMenuItem edit_paste;
    private javax.swing.JButton eight;
    private javax.swing.JButton five;
    private javax.swing.JButton four;
    private javax.swing.JMenu help_menu;
    private javax.swing.JMenuItem help_show;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar menu_bar;
    private javax.swing.JButton minus;
    private javax.swing.JButton multi;
    private javax.swing.JButton multi1;
    private javax.swing.JButton nine;
    private javax.swing.JButton one;
    private javax.swing.JButton one_byx;
    private javax.swing.JLabel operand_bar;
    private javax.swing.JButton plus;
    private javax.swing.JButton plus1;
    private javax.swing.JButton plus_minus;
    private javax.swing.JButton precent;
    private javax.swing.JButton reset;
    private javax.swing.JButton seven;
    private javax.swing.JButton six;
    private javax.swing.JButton sqrt;
    private javax.swing.JButton stand_del;
    private javax.swing.JLabel stand_input;
    private javax.swing.JButton three;
    private javax.swing.JButton two;
    private javax.swing.JMenuItem update;
    private javax.swing.JMenu view_menu;
    private javax.swing.JMenuItem view_programmer;
    private javax.swing.JMenuItem view_sciencetific;
    private javax.swing.JMenuItem view_standard;
    private javax.swing.JButton zero;
    // End of variables declaration//GEN-END:variables
}
